export const TX_SERVICE_HOST = 'tsh'
export const SIGNATURES_VIA_METAMASK = 'svm'
export const RELAY_API_URL = 'rau'
export const BOUNTY_PAYOUT_ADDR = 'bpa'
export const BOUNTY_TOKEN_ADDR = 'bta'
export const SAFE_APPS_URL = 'sau'
